# version: '3'

# services:
#   web:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/code
#     ports:
#       - "8001:8000"


#     depends_on:
#       - db


#   db:
#     image: postgres:11


#     environment:
#       - "POSTGRES_HOST_AUTH_METHOD=trust"



# version: '3'

# services:
#   web:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/code
#     ports:
#       - "8001:8000"

#     depends_on:
#       - db

#   db:
#     image: postgres:11
    # environment:
    #   - POSTGRES_PASSWORD=postgres


  
version: '3'

services:
  web:
    build: .
    # command: python /code/manage.py runserver 0.0.0.0:8000
    command: gunicorn drf_auth.wsgi:application --bind 0.0.0.0:8000 --workers 4
    volumes:
      - .:/code
    ports:
      - 8000:8000
#    depends_on:
#    - db
#
#  db:
#    image: postgres:11
#    environment:
#      - POSTGRES_DB=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
   volumes:
       - postgres_data:/var/lib/postgresql/data/

volumes:
   postgres_data: